### ISSUE TITLE
Various issues

### ISSUE THREAD

**Issue by guytaylor** [sensai7/OpenEuroBoard#1]
I just built two of these are there seem to be some problems.

Not too serious:
1. CV1 and CV2 pots are backwards. CCW = 5V, CW =0V
2. BOM states 7805 for the regulator but this doesn't work, needs to be LM1117-5 (as printed on PCB)
3. LFO 1 is output on LFO 2 pins, and LFO 2 is output on LFO 1 pins

Serious:
4. LFO doesn't appear to work properly. Square wave out does work (but needs buffering if going to euro), but triangle output has no output (I connected it to the LED, it does one cycle and then halts) (I tried numerous different TL074, and TL084 and TL064, All behaved the same on both units)

**Comment by DRnooberson** [comment]
@guytaylor Got the exact same issues as you. Did you have any luck finding a fix for #4 ? These LFO could be very useful for circuit design if they worked properly.

**Comment by sensai7** [comment]
Sorry for neglecting this issue for so long. I've been testing the LFO circuit and found a solution. The oscillator needs a load resistor from the square output to ground so the triangle wave swings all the way. This is something ECAD softwares don't seem to need, but in the real-world circuit a 1k resistor from the sqr output of the LFO to ground does the trick. You can use that as a makeshift fix for the board. it 100% needs a buffer after adding the load resistor.

I'll be updating the git files in the following days addressing all (1~4) issues

**Comment by guytaylor** [comment]
No worries, thanks for the update.
I just tested it, and it's working fine now. Thanks :)

**Comment by DRnooberson** [comment]
Thanks a lot for the support @sensai7 ! This worked like a charm
